using Aquarium.PixelArt;
using UnityEditor;
using UnityEngine;

namespace Aquarium.PixelArt.EditorTools
{
    /// <summary>
    /// Builds the in-scene aquarium environment using pixel-art sprites
    /// generated by <see cref="PixelEnvironmentGenerator"/>. Replaces the
    /// procedural-PNG approach in the legacy <c>AquariumSceneSetup</c>.
    /// </summary>
    public static class PixelAquariumSetup
    {
        public const string TankRootName = "Aquarium_Tank";
        public const float TankHalfWidth = 10.5f;
        public const float TankHalfHeight = 5.25f;

        // Sorting layer assignments must match the layer set created by
        // PixelArtFoundation.EnsureSortingLayers().
        const string LayerBgFar = "BackgroundFar";
        const string LayerBg = "Background";
        const string LayerPlants = "Plants";
        const string LayerEffects = "Effects";
        const string LayerGlass = "Glass";

        // URP default Lit sprite mat ignores Scene tint correctly only when lit.
        // Global Light 2D often has Apply-To-Sorting-Layers unset → Lit sprites render black.
        // Pixel tank decoration should not depend on 2D lighting.
        const string DefaultSpriteUnlitMaterialGuid = "9dfc825aed78fcd4ba02077103263b40";

        [MenuItem("Tools/Aquarium/Pixel Art/4. Setup Pixel Aquarium Scene", false, 130)]
        public static void Setup()
        {
            Undo.IncrementCurrentGroup();

            PixelArtSettings settings = PixelArtFoundation.GetOrCreateSettings();
            (Sprite water, Sprite gravel, Sprite glass, Sprite[] bubbles, Sprite[] plants, Sprite[] corals, Sprite[] silhouettes) =
                PixelEnvironmentGenerator.Generate(settings);

            Transform existing = ResolveTankRoot();
            if (existing != null)
                Undo.DestroyObjectImmediate(existing.gameObject);

            var tankRoot = new GameObject(TankRootName);
            Undo.RegisterCreatedObjectUndo(tankRoot, "Setup Pixel Aquarium");
            tankRoot.transform.position = Vector3.zero;

            BuildBackground(tankRoot.transform, water);
            BuildDistantReef(tankRoot.transform, silhouettes);
            BuildGravelFloor(tankRoot.transform, gravel);
            BuildCorals(tankRoot.transform, corals);
            BuildPlants(tankRoot.transform, plants);
            BuildGlassFrame(tankRoot.transform, glass);
            BuildBubbleEmitter(tankRoot.transform, bubbles);

            Selection.activeGameObject = tankRoot;
            EditorGUIUtility.PingObject(tankRoot);
            Undo.SetCurrentGroupName("Setup Pixel Aquarium Scene");
            Debug.Log("Pixel Aquarium: built tank with pixel water / gravel / plants / glass / bubbles.");
        }

        static Transform ResolveTankRoot()
        {
            GameObject go = GameObject.Find(TankRootName);
            return go != null ? go.transform : null;
        }

        static void BuildBackground(Transform parent, Sprite waterSprite)
        {
            var bg = new GameObject("Aquarium_Background");
            Undo.RegisterCreatedObjectUndo(bg, "Aquarium Background");
            Undo.SetTransformParent(bg.transform, parent, "BG parent");
            bg.transform.position = new Vector3(0f, 0f, 5f);

            SpriteRenderer sr = bg.AddComponent<SpriteRenderer>();
            sr.sprite = waterSprite;
            sr.drawMode = SpriteDrawMode.Sliced;
            sr.size = new Vector2(TankHalfWidth * 2f * 1.05f, TankHalfHeight * 2f * 1.05f);
            sr.color = Color.white;
            ApplyEnvironmentSpriteMaterial(sr);
            SetSorting(sr, LayerBgFar, -200);
        }

        static void BuildDistantReef(Transform parent, Sprite[] silhouettes)
        {
            if (silhouettes == null || silhouettes.Length == 0)
                return;

            var root = new GameObject("Aquarium_DistantReef");
            Undo.RegisterCreatedObjectUndo(root, "Distant Reef Root");
            Undo.SetTransformParent(root.transform, parent, "Distant reef parent");

            for (int i = 0; i < 7; i++)
            {
                Sprite s = silhouettes[i % silhouettes.Length];
                if (s == null) continue;

                var reef = new GameObject($"ReefSilhouette_{i:00}");
                reef.transform.SetParent(root.transform, false);
                float x = -TankHalfWidth + 1.0f + i * 2.1f;
                float y = -TankHalfHeight + 0.68f + (i % 2) * 0.18f;
                reef.transform.localPosition = new Vector3(x, y, 4.8f);
                reef.transform.localScale = new Vector3(1.35f + (i % 3) * 0.15f, 1.0f + (i % 2) * 0.15f, 1f);

                SpriteRenderer sr = reef.AddComponent<SpriteRenderer>();
                sr.sprite = s;
                sr.color = new Color(1f, 1f, 1f, 0.72f);
                ApplyEnvironmentSpriteMaterial(sr);
                SetSorting(sr, LayerBgFar, -185 + i);
            }
        }

        static void BuildGravelFloor(Transform parent, Sprite gravelSprite)
        {
            var floor = new GameObject("Aquarium_Floor");
            Undo.RegisterCreatedObjectUndo(floor, "Aquarium Floor");
            Undo.SetTransformParent(floor.transform, parent, "Floor parent");
            floor.transform.position = new Vector3(0f, -TankHalfHeight + 0.4f, 4.5f);

            SpriteRenderer sr = floor.AddComponent<SpriteRenderer>();
            sr.sprite = gravelSprite;
            sr.drawMode = SpriteDrawMode.Tiled;
            sr.size = new Vector2(TankHalfWidth * 2f * 1.05f, 0.85f);
            ApplyEnvironmentSpriteMaterial(sr);
            SetSorting(sr, LayerBg, -180);
        }

        static void BuildPlants(Transform parent, Sprite[] plantSprites)
        {
            if (plantSprites == null || plantSprites.Length == 0)
                return;

            var root = new GameObject("Aquarium_Plants");
            Undo.RegisterCreatedObjectUndo(root, "Plants Root");
            Undo.SetTransformParent(root.transform, parent, "Plants parent");
            root.transform.position = Vector3.zero;

            // Scatter plants along the gravel line, randomised but
            // deterministic by seed so re-running gives the same look.
            System.Random rng = new System.Random(0x91E25);
            const int count = 13;
            for (int i = 0; i < count; i++)
            {
                Sprite s = plantSprites[rng.Next(0, plantSprites.Length)];
                if (s == null) continue;

                var p = new GameObject($"Plant_{i:00}");
                p.transform.SetParent(root.transform, false);
                float x = ((float)rng.NextDouble() - 0.5f) * (TankHalfWidth * 1.85f);
                float y = -TankHalfHeight + 0.55f + (float)rng.NextDouble() * 0.16f;
                p.transform.localPosition = new Vector3(x, y, 4.0f);

                // Random horizontal flip for variety.
                float scale = 0.82f + (float)rng.NextDouble() * 0.55f;
                if (rng.NextDouble() < 0.5)
                    p.transform.localScale = new Vector3(-scale, scale, 1f);
                else
                    p.transform.localScale = new Vector3(scale, scale, 1f);

                SpriteRenderer sr = p.AddComponent<SpriteRenderer>();
                sr.sprite = s;
                ApplyEnvironmentSpriteMaterial(sr);
                SetSorting(sr, LayerPlants, -150);
            }
        }

        static void BuildCorals(Transform parent, Sprite[] coralSprites)
        {
            if (coralSprites == null || coralSprites.Length == 0)
                return;

            var root = new GameObject("Aquarium_Corals");
            Undo.RegisterCreatedObjectUndo(root, "Corals Root");
            Undo.SetTransformParent(root.transform, parent, "Corals parent");

            float[] xs =
            {
                -TankHalfWidth * 0.88f,
                -TankHalfWidth * 0.72f,
                -TankHalfWidth * 0.49f,
                TankHalfWidth * 0.54f,
                TankHalfWidth * 0.76f,
                TankHalfWidth * 0.90f
            };
            for (int i = 0; i < xs.Length; i++)
            {
                Sprite s = coralSprites[i % coralSprites.Length];
                if (s == null) continue;

                var c = new GameObject($"Coral_{i:00}");
                c.transform.SetParent(root.transform, false);
                c.transform.localPosition = new Vector3(xs[i], -TankHalfHeight + 0.48f, 3.95f);
                float scale = 0.85f + (i % 3) * 0.18f;
                c.transform.localScale = new Vector3(i % 2 == 0 ? scale : -scale, scale, 1f);

                SpriteRenderer sr = c.AddComponent<SpriteRenderer>();
                sr.sprite = s;
                ApplyEnvironmentSpriteMaterial(sr);
                SetSorting(sr, LayerPlants, -145 + i);
            }
        }

        static void BuildGlassFrame(Transform parent, Sprite glass)
        {
            const float thickness = 0.18f;
            const int order = 80;
            Color tint = new Color(0.78f, 0.94f, 1.0f, 0.40f);

            CreateGlassEdge(parent, "Glass_Top", glass, tint, order,
                new Vector3(0f, TankHalfHeight, 0f),
                new Vector2(TankHalfWidth * 2f, thickness));
            CreateGlassEdge(parent, "Glass_Bottom", glass, tint, order,
                new Vector3(0f, -TankHalfHeight, 0f),
                new Vector2(TankHalfWidth * 2f, thickness));
            CreateGlassEdge(parent, "Glass_Left", glass, tint, order,
                new Vector3(-TankHalfWidth, 0f, 0f),
                new Vector2(thickness, TankHalfHeight * 2f));
            CreateGlassEdge(parent, "Glass_Right", glass, tint, order,
                new Vector3(TankHalfWidth, 0f, 0f),
                new Vector2(thickness, TankHalfHeight * 2f));
        }

        static void CreateGlassEdge(Transform parent, string name, Sprite glass, Color tint, int order, Vector3 pos, Vector2 size)
        {
            var go = new GameObject(name);
            Undo.RegisterCreatedObjectUndo(go, "Glass Edge");
            Undo.SetTransformParent(go.transform, parent, "Glass parent");
            go.transform.localPosition = pos;

            SpriteRenderer sr = go.AddComponent<SpriteRenderer>();
            sr.sprite = glass;
            sr.drawMode = SpriteDrawMode.Tiled;
            sr.size = size;
            sr.color = tint;
            ApplyEnvironmentSpriteMaterial(sr);
            SetSorting(sr, LayerGlass, order);
        }

        static void BuildBubbleEmitter(Transform parent, Sprite[] bubbles)
        {
            if (bubbles == null || bubbles.Length == 0)
                return;

            var go = new GameObject("Aquarium_Bubbles");
            Undo.RegisterCreatedObjectUndo(go, "Bubbles");
            Undo.SetTransformParent(go.transform, parent, "Bubbles parent");
            go.transform.position = new Vector3(0f, -TankHalfHeight + 0.3f, 3f);

            ParticleSystem ps = go.AddComponent<ParticleSystem>();
            ParticleSystemRenderer psr = go.GetComponent<ParticleSystemRenderer>();

            // Use Sprites/Default so URP 2D renders the particles.
            Shader unlit = Shader.Find("Sprites/Default");
            if (unlit != null)
                psr.sharedMaterial = new Material(unlit) { name = "M_BubbleParticle" };

            var main = ps.main;
            main.duration = 5f;
            main.loop = true;
            main.startLifetime = 4.5f;
            main.startSize = new ParticleSystem.MinMaxCurve(0.10f, 0.22f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(0.4f, 0.9f);
            main.startColor = new Color(0.85f, 1f, 1f, 0.85f);
            main.simulationSpace = ParticleSystemSimulationSpace.Local;
            main.maxParticles = 80;

            var emission = ps.emission;
            emission.rateOverTime = 6f;

            var shape = ps.shape;
            shape.shapeType = ParticleSystemShapeType.Box;
            shape.scale = new Vector3(TankHalfWidth * 1.7f, 0.05f, 1f);

            var velocity = ps.velocityOverLifetime;
            velocity.enabled = true;
            velocity.x = new ParticleSystem.MinMaxCurve(-0.3f, 0.3f);
            velocity.y = new ParticleSystem.MinMaxCurve(0.4f, 0.9f);
            velocity.z = new ParticleSystem.MinMaxCurve(0f, 0f);

            var ta = ps.textureSheetAnimation;
            ta.enabled = true;
            ta.mode = ParticleSystemAnimationMode.Sprites;
            foreach (Sprite s in bubbles)
                if (s != null) ta.AddSprite(s);
            ta.frameOverTime = new ParticleSystem.MinMaxCurve(0f, 1f); // cycle frames over lifetime

            psr.renderMode = ParticleSystemRenderMode.Billboard;
            SetSortingPS(psr, LayerEffects, -50);
        }

        static void SetSorting(SpriteRenderer sr, string layerName, int order)
        {
            sr.sortingLayerName = layerName;
            sr.sortingOrder = order;
        }

        static void SetSortingPS(ParticleSystemRenderer psr, string layerName, int order)
        {
            psr.sortingLayerName = layerName;
            psr.sortingOrder = order;
        }

        static void ApplyEnvironmentSpriteMaterial(SpriteRenderer sr)
        {
            if (sr == null)
                return;
            string path = AssetDatabase.GUIDToAssetPath(DefaultSpriteUnlitMaterialGuid);
            if (string.IsNullOrEmpty(path))
                return;
            Material m = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (m != null)
                sr.sharedMaterial = m;
        }
    }
}
